DROP TABLE IF EXISTS REQUEST;

CREATE TABLE REQUEST (
  LOGIN VARCHAR(250) PRIMARY KEY,
  REQUEST_COUNT INT NOT NULL
);

INSERT INTO REQUEST (LOGIN, REQUEST_COUNT) VALUES
  ('octocat', 0),
  ('mfurmane', 0);